### ISSUE TITLE
Hamburger menu is in the middle of the page!

### ISSUE THREAD

**Issue by ajilenakh** [SleepyMiner/Aeroplane-Website#3]
![image](https://github.com/SleepyMiner/Aeroplane-Website/assets/107887918/48e48865-07ec-4382-a4c1-0504672226e1)

**Comment by SleepyMiner** [comment]
fixed the bug

**Comment by SleepyMiner** [comment]
![Screenshot 2023-09-24 171733](https://github.com/SleepyMiner/Aeroplane-Website/assets/90234481/326bf4e9-caf9-48a2-b3a1-ec9108284aa3)
the bug is fixed
